/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LinkMentionPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/reading-view.ts
var import_obsidian2 = require("obsidian");

// src/metadata.ts
var import_obsidian = require("obsidian");

// src/parsers/html.ts
function extractFaviconUrl(doc, pageUrl) {
  const selectors = [
    'link[rel="icon"]',
    'link[rel="shortcut icon"]',
    'link[rel="apple-touch-icon"]'
  ];
  for (const sel of selectors) {
    const el = doc.querySelector(sel);
    const href = el == null ? void 0 : el.getAttribute("href");
    if (href) {
      try {
        return new URL(href, pageUrl).href;
      } catch (e) {
        continue;
      }
    }
  }
  return null;
}
function extractOgTitle(doc) {
  var _a, _b;
  return ((_b = (_a = doc.querySelector('meta[property="og:title"]')) == null ? void 0 : _a.getAttribute("content")) == null ? void 0 : _b.trim()) || void 0;
}
function extractAuthor(doc) {
  var _a, _b;
  return ((_b = (_a = doc.querySelector('meta[name="author"]')) == null ? void 0 : _a.getAttribute("content")) == null ? void 0 : _b.trim()) || void 0;
}
function extractDocTitle(doc) {
  var _a, _b;
  const raw = (_b = (_a = doc.querySelector("title")) == null ? void 0 : _a.textContent) == null ? void 0 : _b.trim();
  if (!raw) {
    return void 0;
  }
  const segment = raw.split(/\s*[·|—]\s*/)[0].trim();
  return segment || void 0;
}
function extractGithubTitle(doc) {
  var _a, _b;
  const ogTitle = extractOgTitle(doc);
  if (ogTitle) {
    const withoutDesc = ogTitle.split(":")[0].trim();
    return ((_a = withoutDesc.split("/").pop()) == null ? void 0 : _a.trim()) || void 0;
  }
  const docTitle = extractDocTitle(doc);
  if (docTitle) {
    const withoutDesc = docTitle.split(":")[0].trim();
    return ((_b = withoutDesc.split("/").pop()) == null ? void 0 : _b.trim()) || void 0;
  }
  return void 0;
}

// src/parsers/url.ts
var REDDIT_POST_RE = /^\/r\/([^/]+)\/comments\/[^/]+\/([^/]+)/;
function extractRedditTitle(url) {
  let parsed;
  try {
    parsed = new URL(url);
  } catch (e) {
    return void 0;
  }
  const host = parsed.hostname;
  if (host !== "reddit.com" && host !== "www.reddit.com" && host !== "old.reddit.com") {
    return void 0;
  }
  const match = REDDIT_POST_RE.exec(parsed.pathname);
  if (!match) {
    const subMatch = /^\/r\/([^/]+)/.exec(parsed.pathname);
    if (subMatch) {
      return { title: `r/${subMatch[1]}`, author: "" };
    }
    const userMatch = /^\/user\/([^/]+)/.exec(parsed.pathname);
    if (userMatch) {
      return { title: `u/${userMatch[1]}`, author: "" };
    }
    return void 0;
  }
  const subreddit = match[1];
  const slug = decodeURIComponent(match[2]);
  const title = slug.split(/[-_\s]+/).filter((w) => w.length > 0).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
  return title ? { title, author: `r/${subreddit}` } : void 0;
}
function extractUrlTitle(url) {
  let parsed;
  try {
    parsed = new URL(url);
  } catch (e) {
    return url;
  }
  const segments = parsed.pathname.split("/").map((s) => decodeURIComponent(s)).filter(Boolean);
  let best;
  for (const seg of segments) {
    const cleaned = seg.replace(/[?=&].*/, "");
    const words = cleaned.split(/[-_\s]+/).filter((w) => w.length > 0);
    if (words.length < 2) {
      continue;
    }
    if (words.join("").length < 10) {
      continue;
    }
    if (!best || cleaned.length > best.length) {
      best = cleaned;
    }
  }
  if (!best) {
    return parsed.hostname;
  }
  return best.split(/[-_\s]+/).filter((w) => w.length > 0).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
}

// src/metadata.ts
var cache = /* @__PURE__ */ new Map();
var inflight = /* @__PURE__ */ new Map();
var failedUntil = /* @__PURE__ */ new Map();
var MAX_HTML_BYTES = 51200;
var maxConcurrent = 4;
var activeCount = 0;
var waiting = [];
function setMaxConcurrent(n) {
  maxConcurrent = n;
}
function acquireSlot() {
  if (activeCount < maxConcurrent) {
    activeCount++;
    return Promise.resolve();
  }
  return new Promise((resolve) => waiting.push(resolve));
}
function releaseSlot() {
  activeCount--;
  const next = waiting.shift();
  if (next) {
    activeCount++;
    next();
  }
}
function normalizeUrl(raw) {
  try {
    return new URL(raw).href;
  } catch (e) {
    return raw;
  }
}
function getContentType(headers) {
  for (const key of Object.keys(headers)) {
    if (key.toLowerCase() === "content-type") {
      return headers[key].split(";")[0].trim();
    }
  }
  return "image/png";
}
function fetchFavicon(pageUrl, doc) {
  if (doc) {
    const fromHtml = extractFaviconUrl(doc, pageUrl);
    if (fromHtml) {
      return fromHtml;
    }
  }
  try {
    return new URL("/favicon.ico", pageUrl).href;
  } catch (e) {
    return "";
  }
}
var OEMBED_ENDPOINTS = [
  {
    pattern: /^https?:\/\/(www\.)?youtube\.com\/watch/,
    endpoint: "https://www.youtube.com/oembed?format=json&url="
  },
  {
    pattern: /^https?:\/\/youtu\.be\//,
    endpoint: "https://www.youtube.com/oembed?format=json&url="
  },
  {
    pattern: /^https?:\/\/(www\.)?vimeo\.com\/\d+/,
    endpoint: "https://vimeo.com/api/oembed.json?url="
  }
];
async function fetchOembed(url) {
  var _a, _b, _c, _d, _e;
  for (const { pattern, endpoint } of OEMBED_ENDPOINTS) {
    if (pattern.test(url)) {
      try {
        const response = await (0, import_obsidian.requestUrl)({
          url: `${endpoint}${encodeURIComponent(url)}`,
          method: "GET"
        });
        const title = (_b = (_a = response.json) == null ? void 0 : _a.title) == null ? void 0 : _b.trim();
        if (!title) {
          return void 0;
        }
        const author = (_e = (_d = (_c = response.json) == null ? void 0 : _c.author_name) == null ? void 0 : _d.trim()) != null ? _e : "";
        return { title, author };
      } catch (e) {
        return void 0;
      }
    }
  }
  return void 0;
}
async function doFetch(url) {
  var _a;
  let doc = null;
  const oembed = await fetchOembed(url);
  if (oembed) {
    const favicon2 = fetchFavicon(url, null);
    return { title: oembed.title, favicon: favicon2, author: oembed.author };
  }
  const response = await (0, import_obsidian.requestUrl)({
    url,
    method: "GET",
    headers: { Range: `bytes=0-${MAX_HTML_BYTES}` },
    throw: false
  });
  const ct = getContentType(response.headers);
  if (!ct.startsWith("text/html")) {
    const title2 = extractUrlTitle(url);
    const favicon2 = fetchFavicon(url, null);
    return { title: title2, favicon: favicon2, author: "" };
  }
  const html = response.text.slice(0, MAX_HTML_BYTES);
  doc = new DOMParser().parseFromString(html, "text/html");
  let title;
  try {
    const hostname = new URL(url).hostname;
    if (hostname === "github.com" || hostname === "www.github.com") {
      title = extractGithubTitle(doc);
    }
    if (hostname === "reddit.com" || hostname === "www.reddit.com" || hostname === "old.reddit.com") {
      const reddit = extractRedditTitle(url);
      if (reddit) {
        const favicon2 = fetchFavicon(url, doc);
        return { title: reddit.title, favicon: favicon2, author: reddit.author };
      }
    }
  } catch (e) {
  }
  title != null ? title : title = (_a = extractDocTitle(doc)) != null ? _a : extractOgTitle(doc);
  if (!title) {
    title = extractUrlTitle(url);
  }
  const author = extractAuthor(doc);
  const favicon = fetchFavicon(url, doc);
  return { title, favicon, author: author != null ? author : "" };
}
function getCachedMetadata(url) {
  return cache.get(normalizeUrl(url));
}
async function fetchLinkMetadata(url) {
  const normalized = normalizeUrl(url);
  const cached = cache.get(normalized);
  if (cached) {
    return cached;
  }
  const failUntil = failedUntil.get(normalized);
  if (failUntil && Date.now() < failUntil) {
    const title = extractUrlTitle(normalized);
    return { title, favicon: "", author: "" };
  }
  let pending = inflight.get(normalized);
  if (pending) {
    return pending;
  }
  pending = acquireSlot().then(() => doFetch(normalized)).finally(releaseSlot).then((meta) => {
    cache.set(normalized, meta);
    inflight.delete(normalized);
    return meta;
  }).catch(() => {
    inflight.delete(normalized);
    failedUntil.set(normalized, Date.now() + 6e4);
    const title = extractUrlTitle(normalized);
    return { title, favicon: "", author: "" };
  });
  inflight.set(normalized, pending);
  return pending;
}

// src/reading-view.ts
function createPill(title, favicon, href, author = "") {
  const pill = document.createElement("a");
  pill.className = "link-mention external-link";
  pill.href = href;
  pill.title = href;
  pill.setAttribute("target", "_blank");
  pill.setAttribute("rel", "noopener noreferrer");
  if (favicon) {
    const img = document.createElement("img");
    img.className = "link-mention-favicon";
    img.src = favicon;
    img.alt = "";
    img.setAttribute("width", "19");
    img.setAttribute("height", "19");
    img.addEventListener("error", () => {
      const iconEl = document.createElement("span");
      iconEl.className = "link-mention-favicon link-mention-default-icon";
      (0, import_obsidian2.setIcon)(iconEl, "link");
      img.replaceWith(iconEl);
    });
    pill.appendChild(img);
  } else {
    const iconEl = document.createElement("span");
    iconEl.className = "link-mention-favicon link-mention-default-icon";
    (0, import_obsidian2.setIcon)(iconEl, "link");
    pill.appendChild(iconEl);
  }
  if (author) {
    const authorSpan = document.createElement("span");
    authorSpan.className = "link-mention-author";
    authorSpan.textContent = author;
    pill.appendChild(authorSpan);
  }
  const span = document.createElement("span");
  span.className = "link-mention-title";
  span.textContent = title;
  pill.appendChild(span);
  return pill;
}
function isEmptyTextLink(el) {
  var _a;
  const href = el.getAttribute("href") || "";
  const text = ((_a = el.textContent) == null ? void 0 : _a.trim()) || "";
  return text === "" || text === href;
}
function readingViewPostProcessor(el, _ctx) {
  const links = el.querySelectorAll("a.external-link");
  for (const link of Array.from(links)) {
    if (!isEmptyTextLink(link)) {
      continue;
    }
    const href = link.getAttribute("href");
    if (!href) {
      continue;
    }
    const cached = getCachedMetadata(href);
    if (cached) {
      const pill = createPill(cached.title, cached.favicon, href, cached.author);
      link.replaceWith(pill);
    } else {
      const placeholderTitle = extractUrlTitle(href);
      const placeholder = createPill(placeholderTitle, "", href);
      link.replaceWith(placeholder);
      void fetchLinkMetadata(href).then((meta) => {
        const pill = createPill(meta.title, meta.favicon, href, meta.author);
        placeholder.replaceWith(pill);
      });
    }
  }
}

// src/live-preview.ts
var import_view = require("@codemirror/view");
var import_obsidian3 = require("obsidian");
var LinkMentionWidget = class extends import_view.WidgetType {
  constructor(url, meta) {
    super();
    this.url = url;
    this.meta = meta;
  }
  /** Two widgets are equal if they point to the same URL with the same title. */
  eq(other) {
    return this.url === other.url && this.meta.title === other.meta.title && this.meta.author === other.meta.author;
  }
  /** Builds the pill `<a>` element with favicon, title, and click handling. */
  toDOM() {
    const pill = document.createElement("a");
    pill.className = "link-mention external-link";
    pill.href = this.url;
    pill.title = this.url;
    pill.setAttribute("target", "_blank");
    pill.setAttribute("rel", "noopener noreferrer");
    if (this.meta.favicon) {
      const img = document.createElement("img");
      img.className = "link-mention-favicon";
      img.src = this.meta.favicon;
      img.alt = "";
      img.setAttribute("width", "19");
      img.setAttribute("height", "19");
      img.addEventListener("error", () => {
        const iconEl = document.createElement("span");
        iconEl.className = "link-mention-favicon link-mention-default-icon";
        (0, import_obsidian3.setIcon)(iconEl, "link");
        img.replaceWith(iconEl);
      });
      pill.appendChild(img);
    } else {
      const iconEl = document.createElement("span");
      iconEl.className = "link-mention-favicon link-mention-default-icon";
      (0, import_obsidian3.setIcon)(iconEl, "link");
      pill.appendChild(iconEl);
    }
    if (this.meta.author) {
      const author = document.createElement("span");
      author.className = "link-mention-author";
      author.textContent = this.meta.author;
      pill.appendChild(author);
    }
    const span = document.createElement("span");
    span.className = "link-mention-title";
    span.textContent = this.meta.title;
    pill.appendChild(span);
    pill.addEventListener("mousedown", (e) => {
      if (e.button !== 0 || e.altKey || e.ctrlKey || e.metaKey) {
        return;
      }
      e.preventDefault();
      if (e.button === 0 && !e.altKey && !e.ctrlKey && !e.metaKey) {
        e.stopPropagation();
      }
    });
    pill.addEventListener("click", (e) => {
      if (e.button !== 0 || e.altKey || e.ctrlKey || e.metaKey) {
        return;
      }
      e.preventDefault();
      e.stopPropagation();
      window.open(this.url, "_blank");
    });
    return pill;
  }
  ignoreEvent() {
    return true;
  }
};
var EMPTY_LINK_RE = /\[]\((https?:\/\/(?:[^()\r\n]|\([^()\r\n]*\))+)\)/g;
function cursorInRange(selection, from, to) {
  return selection.ranges.some((range) => range.from >= from && range.to <= to);
}
function getSelectedSearchRange(view) {
  var _a;
  const leaf = view.dom.closest(".workspace-leaf-content");
  if (!leaf) {
    return null;
  }
  const input = leaf.querySelector(".document-search-container input");
  const query = input == null ? void 0 : input.value;
  if (!query) {
    return null;
  }
  const counter = leaf.querySelector(".document-search-count");
  const m = (_a = counter == null ? void 0 : counter.textContent) == null ? void 0 : _a.match(/(\d+)\s*\/\s*(\d+)/);
  if (!m) {
    return null;
  }
  const currentIndex = parseInt(m[1], 10) - 1;
  if (currentIndex < 0) {
    return null;
  }
  const text = view.state.doc.toString().toLowerCase();
  const lowerQuery = query.toLowerCase();
  let idx = 0;
  for (let i = 0; i <= currentIndex; i++) {
    const pos = text.indexOf(lowerQuery, idx);
    if (pos === -1) {
      return null;
    }
    if (i === currentIndex) {
      return { from: pos, to: pos + query.length };
    }
    idx = pos + 1;
  }
  return null;
}
function buildDecorations(view, onFetchComplete) {
  const decorations = [];
  const links = [];
  const doc = view.state.doc;
  const selectedSearch = getSelectedSearchRange(view);
  EMPTY_LINK_RE.lastIndex = 0;
  for (const { from, to } of view.visibleRanges) {
    const text = doc.sliceString(from, to);
    EMPTY_LINK_RE.lastIndex = 0;
    let match;
    while ((match = EMPTY_LINK_RE.exec(text)) !== null) {
      const matchFrom = from + match.index;
      const matchTo = matchFrom + match[0].length;
      const url = match[1];
      links.push({ from: matchFrom, to: matchTo, url });
      if (cursorInRange(view.state.selection, matchFrom, matchTo)) {
        continue;
      }
      if (selectedSearch && selectedSearch.from >= matchFrom && selectedSearch.from < matchTo) {
        continue;
      }
      const meta = getCachedMetadata(url);
      if (meta) {
        decorations.push(
          import_view.Decoration.replace({
            widget: new LinkMentionWidget(url, meta)
          }).range(matchFrom, matchTo)
        );
      } else {
        void fetchLinkMetadata(url).then(onFetchComplete);
      }
    }
  }
  return { decorations: import_view.Decoration.set(decorations, true), links };
}
function rebuildFromKnown(view, knownLinks, onFetchComplete) {
  const decorations = [];
  const selectedSearch = getSelectedSearchRange(view);
  for (const { from, to, url } of knownLinks) {
    if (cursorInRange(view.state.selection, from, to)) {
      continue;
    }
    if (selectedSearch && selectedSearch.from >= from && selectedSearch.from < to) {
      continue;
    }
    const meta = getCachedMetadata(url);
    if (meta) {
      decorations.push(
        import_view.Decoration.replace({
          widget: new LinkMentionWidget(url, meta)
        }).range(from, to)
      );
    } else {
      void fetchLinkMetadata(url).then(onFetchComplete);
    }
  }
  return import_view.Decoration.set(decorations, true);
}
var livePreviewExtension = import_view.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.hasPendingFetches = false;
      this.searchNeedsRebuild = false;
      this.knownLinks = [];
      this.dispatchTimer = null;
      this.searchObserver = null;
      this.searchInput = null;
      this.searchDebounce = null;
      /**
       * Debounced trigger for search-related rebuilds. Waits briefly so
       * Obsidian has time to update the "X / Y" counter after keydown
       * events (Enter, arrows) before we read it.
       */
      this.scheduleSearchRebuild = () => {
        if (this.searchDebounce) {
          clearTimeout(this.searchDebounce);
        }
        this.searchDebounce = setTimeout(() => {
          this.searchDebounce = null;
          this.searchNeedsRebuild = true;
          this.view.dispatch();
        }, 30);
      };
      this.view = view;
      const onFetch = () => this.scheduleDispatch(view);
      const result = buildDecorations(view, onFetch);
      this.decorations = result.decorations;
      this.knownLinks = result.links;
      const leaf = view.dom.closest(".workspace-leaf-content");
      if (leaf) {
        this.searchObserver = new MutationObserver(() => {
          const input = leaf.querySelector(".document-search-container input");
          if (input && input !== this.searchInput) {
            this.detachSearchInput();
            this.searchInput = input;
            this.searchInput.addEventListener("input", this.scheduleSearchRebuild);
            this.searchInput.addEventListener("keydown", this.scheduleSearchRebuild);
            this.scheduleSearchRebuild();
          } else if (!input && this.searchInput) {
            this.detachSearchInput();
            this.scheduleSearchRebuild();
          }
        });
        this.searchObserver.observe(leaf, { childList: true, subtree: true });
      }
    }
    detachSearchInput() {
      if (this.searchInput) {
        this.searchInput.removeEventListener("input", this.scheduleSearchRebuild);
        this.searchInput.removeEventListener("keydown", this.scheduleSearchRebuild);
        this.searchInput = null;
      }
    }
    destroy() {
      var _a;
      (_a = this.searchObserver) == null ? void 0 : _a.disconnect();
      this.detachSearchInput();
      if (this.searchDebounce) {
        clearTimeout(this.searchDebounce);
      }
      if (this.dispatchTimer) {
        clearTimeout(this.dispatchTimer);
      }
    }
    /**
     * Debounces `view.dispatch()` so multiple fetch completions within
     * 50ms trigger a single re-render instead of one per fetch.
     */
    scheduleDispatch(view) {
      this.hasPendingFetches = true;
      if (this.dispatchTimer) {
        return;
      }
      this.dispatchTimer = setTimeout(() => {
        this.dispatchTimer = null;
        view.dispatch();
      }, 50);
    }
    update(update) {
      this.view = update.view;
      const onFetch = () => this.scheduleDispatch(update.view);
      if (update.docChanged || update.viewportChanged) {
        this.hasPendingFetches = false;
        this.searchNeedsRebuild = false;
        const result = buildDecorations(update.view, onFetch);
        this.decorations = result.decorations;
        this.knownLinks = result.links;
      } else if (update.state.selection !== update.startState.selection || this.hasPendingFetches || this.searchNeedsRebuild) {
        this.hasPendingFetches = false;
        this.searchNeedsRebuild = false;
        this.decorations = rebuildFromKnown(update.view, this.knownLinks, onFetch);
      }
    }
  },
  {
    decorations: (v) => v.decorations,
    eventHandlers: {
      mousedown(event, view) {
        if (event.button !== 0 || event.altKey || event.ctrlKey || event.metaKey) {
          return;
        }
        const target = event.target;
        const icon = target.closest(".external-link");
        if (!icon || icon.classList.contains("link-mention")) {
          return;
        }
        const pos = view.posAtDOM(icon);
        const link = this.knownLinks.find((l) => pos >= l.from && pos <= l.to + 2);
        if (link) {
          event.preventDefault();
          event.stopPropagation();
        }
      },
      click(event, view) {
        if (event.button !== 0 || event.altKey || event.ctrlKey || event.metaKey) {
          return;
        }
        const target = event.target;
        const icon = target.closest(".external-link");
        if (!icon || icon.classList.contains("link-mention")) {
          return;
        }
        const pos = view.posAtDOM(icon);
        const link = this.knownLinks.find((l) => pos >= l.from && pos <= l.to + 2);
        if (link) {
          event.preventDefault();
          event.stopPropagation();
          window.open(link.url, "_blank");
        }
      }
    }
  }
);

// src/main.ts
var DEFAULT_CONCURRENT_FETCHES = 4;
var MAX_CONCURRENT_LIMIT = 30;
var DEFAULT_SETTINGS = {
  showExternalArrow: true,
  maxConcurrentFetches: DEFAULT_CONCURRENT_FETCHES
};
var HIDE_ARROW_CLASS = "link-mention-hide-arrow";
var LinkMentionPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    setMaxConcurrent(this.settings.maxConcurrentFetches);
    this.applyBodyClass();
    this.addSettingTab(new LinkMentionSettingTab(this.app, this));
    this.registerMarkdownPostProcessor(readingViewPostProcessor);
    this.registerEditorExtension(livePreviewExtension);
  }
  onunload() {
    document.body.classList.remove(HIDE_ARROW_CLASS);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.applyBodyClass();
  }
  applyBodyClass() {
    document.body.classList.toggle(HIDE_ARROW_CLASS, !this.settings.showExternalArrow);
  }
};
var LinkMentionSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName("Show external link arrow").setDesc("Show Obsidian's external-link arrow icon next to link mention pills.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showExternalArrow).onChange(async (value) => {
        this.plugin.settings.showExternalArrow = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Max concurrent fetches").setDesc(
      "Number of link metadata requests that can run in parallel. Higher values populate pills faster but may cause rate limiting."
    ).addSlider(
      (slider) => slider.setLimits(1, MAX_CONCURRENT_LIMIT, 1).setValue(this.plugin.settings.maxConcurrentFetches).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.maxConcurrentFetches = value;
        setMaxConcurrent(value);
        await this.plugin.saveSettings();
      })
    );
  }
};

/* nosourcemap */