/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ImageAlignmentPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/body-classes.ts
function applyImageAlignmentBodyClasses(settings, targetDocument = document) {
  clearImageAlignmentBodyClasses(targetDocument);
  targetDocument.body.classList.add(`image-alignment-default-${settings.defaultAlignment}`);
}
function clearImageAlignmentBodyClasses(targetDocument = document) {
  for (const alignment of ["center", "left", "right"]) {
    targetDocument.body.classList.remove(`image-alignment-default-${alignment}`);
    targetDocument.body.classList.remove(`image-alignment-menu-default-${alignment}`);
  }
}

// src/dom.ts
function isHTMLElement(value) {
  var _a, _b;
  if (!value || typeof value !== "object") {
    return false;
  }
  const ownerDocument = value.ownerDocument;
  const HTMLElementConstructor = (_b = (_a = ownerDocument == null ? void 0 : ownerDocument.defaultView) == null ? void 0 : _a.HTMLElement) != null ? _b : HTMLElement;
  return value instanceof HTMLElementConstructor;
}
function isElement(value) {
  var _a, _b;
  if (!value || typeof value !== "object") {
    return false;
  }
  const ownerDocument = value.ownerDocument;
  const ElementConstructor = (_b = (_a = ownerDocument == null ? void 0 : ownerDocument.defaultView) == null ? void 0 : _a.Element) != null ? _b : Element;
  return value instanceof ElementConstructor;
}
function isInMarkdownContent(element) {
  return Boolean(element.closest(".markdown-source-view, .markdown-preview-view"));
}

// src/image-markdown.ts
var WIKI_IMAGE_PATTERN = /!\[\[(.*?)\]\]/g;
var MARKDOWN_IMAGE_PATTERN = /!\[([^\]]*)\]\(([^)]+)\)/g;
var ALIGNMENT_TOKENS = /* @__PURE__ */ new Set(["left", "right", "center"]);
function findImageNearPosition(line, ch) {
  const matches = findImagesInLine(line);
  if (matches.length === 0) {
    return null;
  }
  const containing = matches.find((match) => match.from <= ch && ch <= match.to);
  if (containing) {
    return containing;
  }
  return matches.reduce((nearest, match) => {
    const nearestDistance = distanceToRange(ch, nearest.from, nearest.to);
    const matchDistance = distanceToRange(ch, match.from, match.to);
    return matchDistance < nearestDistance ? match : nearest;
  });
}
function findImagesInLine(line) {
  const matches = [];
  for (const match of line.matchAll(WIKI_IMAGE_PATTERN)) {
    if (match.index === void 0) {
      continue;
    }
    matches.push({
      from: match.index,
      to: match.index + match[0].length,
      value: match[0]
    });
  }
  for (const match of line.matchAll(MARKDOWN_IMAGE_PATTERN)) {
    if (match.index === void 0) {
      continue;
    }
    matches.push({
      from: match.index,
      to: match.index + match[0].length,
      value: match[0]
    });
  }
  return matches.sort((a, b) => a.from - b.from);
}
function findImageInSelection(editor) {
  const selection = editor.getSelection();
  if (!selection) {
    return null;
  }
  const from = editor.getCursor("from");
  const selectedLines = selection.split(/\r?\n/);
  for (let lineOffset = 0; lineOffset < selectedLines.length; lineOffset += 1) {
    const matches = findImagesInLine(selectedLines[lineOffset]);
    const match = matches[0];
    if (!match) {
      continue;
    }
    const line = from.line + lineOffset;
    const chOffset = lineOffset === 0 ? from.ch : 0;
    return {
      editor,
      line,
      match: {
        from: chOffset + match.from,
        to: chOffset + match.to,
        value: match.value
      }
    };
  }
  return null;
}
function setImageAlignment(markdown, alignment, defaultAlignment) {
  if (markdown.startsWith("![[")) {
    return setWikiImageAlignment(markdown, alignment, defaultAlignment);
  }
  return setMarkdownImageAlignment(markdown, alignment, defaultAlignment);
}
function getImageSourceFromElement(element) {
  var _a, _b;
  const embed = (_a = element.closest(".image-embed")) != null ? _a : element;
  const source = (_b = embed.getAttribute("src")) != null ? _b : element.getAttribute("src");
  if (!source) {
    return null;
  }
  return decodeURIComponent(source).replace(/^app:\/\/[^/]+\//, "").replace(/^.*[\\/](?=attachments[\\/])/, "").replace(/\\/g, "/");
}
function imageMatchHasSource(markdown, imageSource) {
  return getImageSourceFromMarkdown(markdown) === imageSource;
}
function distanceToRange(ch, from, to) {
  if (ch < from) {
    return from - ch;
  }
  if (ch > to) {
    return ch - to;
  }
  return 0;
}
function setWikiImageAlignment(markdown, alignment, defaultAlignment) {
  var _a;
  const inner = markdown.slice(3, -2);
  const parts = inner.split("|");
  const target = (_a = parts.shift()) != null ? _a : "";
  const modifiers = removeAlignmentTokens(parts);
  if (alignment !== defaultAlignment) {
    modifiers.unshift(alignment);
  }
  return modifiers.length > 0 ? `![[${[target, ...modifiers].join("|")}]]` : `![[${target}]]`;
}
function setMarkdownImageAlignment(markdown, alignment, defaultAlignment) {
  const match = markdown.match(/^!\[([^\]]*)\]\(([^)]+)\)$/);
  if (!match) {
    return markdown;
  }
  const altParts = match[1].split("|").filter((part) => part.length > 0);
  const alt = removeAlignmentTokens(altParts);
  if (alignment !== defaultAlignment) {
    alt.unshift(alignment);
  }
  return `![${alt.join("|")}](${match[2]})`;
}
function removeAlignmentTokens(values) {
  return values.filter((value) => !ALIGNMENT_TOKENS.has(value.trim().toLowerCase()));
}
function getImageSourceFromMarkdown(markdown) {
  var _a;
  if (markdown.startsWith("![[")) {
    const inner = markdown.slice(3, -2);
    const target = (_a = inner.split("|")[0]) != null ? _a : "";
    return target.replace(/\\/g, "/");
  }
  const match = markdown.match(/^!\[[^\]]*]\(([^)]+)\)$/);
  return match ? match[1].replace(/\\/g, "/") : null;
}

// src/image-size.ts
var CALLOUT_IMAGE_SELECTOR = [
  ".markdown-preview-view .callout .image-embed",
  ".markdown-source-view.mod-cm6.is-live-preview .callout .image-embed",
  ".markdown-source-view.mod-cm6.is-live-preview .HyperMD-quote > .image-embed"
].join(", ");
var SYNCED_IMAGE_SIZE_ATTRIBUTE = "data-image-alignment-callout-size-synced";
function syncCalloutImageSizes(targetDocument = document) {
  for (const imageElement of targetDocument.querySelectorAll(CALLOUT_IMAGE_SELECTOR)) {
    syncImageSize(imageElement);
  }
}
function clearCalloutImageSizeSync(targetDocument = document) {
  for (const image of targetDocument.querySelectorAll(`img[${SYNCED_IMAGE_SIZE_ATTRIBUTE}]`)) {
    clearSyncedImageSize(image);
  }
}
function syncImageSize(imageElement) {
  var _a, _b;
  const image = imageElement.querySelector("img");
  if (!image) {
    return;
  }
  const width = (_a = getPositiveIntegerAttribute(imageElement, "width")) != null ? _a : getPositiveIntegerAttribute(image, "width");
  const height = (_b = getPositiveIntegerAttribute(imageElement, "height")) != null ? _b : getPositiveIntegerAttribute(image, "height");
  if (!width) {
    clearSyncedImageSize(image);
    return;
  }
  image.setAttribute(SYNCED_IMAGE_SIZE_ATTRIBUTE, "");
  image.setCssProps({
    "--image-alignment-synced-width": `${width}px`,
    "--image-alignment-synced-height": height ? `${height}px` : "auto"
  });
}
function clearSyncedImageSize(image) {
  image.setCssProps({
    "--image-alignment-synced-width": "",
    "--image-alignment-synced-height": ""
  });
  image.removeAttribute(SYNCED_IMAGE_SIZE_ATTRIBUTE);
}
function getPositiveIntegerAttribute(element, attribute) {
  const value = Number(element.getAttribute(attribute));
  return Number.isInteger(value) && value > 0 ? value : null;
}

// src/live-preview-edit.ts
var EDIT_TOOLTIP_ALIGNMENT_ATTRIBUTE = "data-image-alignment-live-preview-edit";
var nativeEditAlignmentStates = /* @__PURE__ */ new Map();
var originalTooltipTranslations = /* @__PURE__ */ new WeakMap();
function preserveLivePreviewImageDuringNativeEdit(event, defaultAlignment) {
  if (event.button !== 0) {
    return;
  }
  const target = event.target;
  if (!isElement(target)) {
    return;
  }
  const editButton = target.closest(".edit-block-button");
  if (!editButton) {
    return;
  }
  const imageElement = editButton.closest(".image-embed");
  const sourceView = imageElement == null ? void 0 : imageElement.closest(
    ".markdown-source-view.mod-cm6.is-live-preview"
  );
  if (!imageElement || !sourceView) {
    return;
  }
  if (event.type === "click" && nativeEditAlignmentStates.has(sourceView)) {
    return;
  }
  startNativeEditAlignment(
    sourceView,
    getImageAlignment(imageElement, defaultAlignment),
    imageElement.getBoundingClientRect().top
  );
}
function clearLivePreviewImageEditPreviews(targetDocument = document) {
  for (const sourceView of nativeEditAlignmentStates.keys()) {
    if (sourceView.ownerDocument === targetDocument) {
      clearNativeEditAlignment(sourceView);
    }
  }
}
function startNativeEditAlignment(sourceView, alignment, targetTop) {
  var _a, _b;
  const previousTooltip = (_a = findNativeEditTooltips(sourceView)[0]) != null ? _a : null;
  disposeNativeEditAlignment(sourceView, false);
  const ownerWindow = (_b = sourceView.ownerDocument.defaultView) != null ? _b : window;
  const state = {
    activationTimeoutId: null,
    alignment,
    mutationObserver: new ownerWindow.MutationObserver(() => {
      syncNativeEditTooltip(sourceView);
    }),
    previousTooltip,
    resizeObserver: new ownerWindow.ResizeObserver(() => {
      positionNativeEditTooltip(sourceView);
    }),
    targetTop,
    tooltip: null,
    translateX: null,
    translateY: null
  };
  state.mutationObserver.observe(sourceView, {
    childList: true,
    subtree: true
  });
  nativeEditAlignmentStates.set(sourceView, state);
  ownerWindow.setTimeout(() => syncNativeEditTooltip(sourceView), 0);
  state.activationTimeoutId = ownerWindow.setTimeout(() => {
    var _a2;
    const currentState = nativeEditAlignmentStates.get(sourceView);
    if (!currentState || currentState.tooltip) {
      return;
    }
    disposeNativeEditAlignment(
      sourceView,
      !((_a2 = currentState.previousTooltip) == null ? void 0 : _a2.isConnected)
    );
  }, 1e3);
}
function syncNativeEditTooltip(sourceView) {
  var _a, _b;
  const state = nativeEditAlignmentStates.get(sourceView);
  if (!state) {
    return;
  }
  if (state.previousTooltip && !state.previousTooltip.isConnected) {
    clearTooltipAlignment(state.previousTooltip);
    state.previousTooltip = null;
  }
  const tooltip = (_a = findNativeEditTooltips(sourceView).find(
    (candidate) => candidate !== state.previousTooltip
  )) != null ? _a : null;
  if (!tooltip) {
    if (state.tooltip && !state.tooltip.isConnected) {
      clearNativeEditAlignment(sourceView);
    }
    return;
  }
  if (state.tooltip !== tooltip) {
    clearTooltipAlignment(state.tooltip);
    state.resizeObserver.disconnect();
    state.translateX = null;
    state.translateY = null;
    state.tooltip = tooltip;
    state.resizeObserver.observe(tooltip);
    const content = sourceView.querySelector(".cm-content");
    if (content) {
      state.resizeObserver.observe(content);
    }
  }
  if (state.activationTimeoutId !== null) {
    ((_b = sourceView.ownerDocument.defaultView) != null ? _b : window).clearTimeout(
      state.activationTimeoutId
    );
    state.activationTimeoutId = null;
  }
  tooltip.setAttribute(EDIT_TOOLTIP_ALIGNMENT_ATTRIBUTE, state.alignment);
  positionNativeEditTooltip(sourceView);
}
function positionNativeEditTooltip(sourceView) {
  var _a;
  const state = nativeEditAlignmentStates.get(sourceView);
  const tooltip = state == null ? void 0 : state.tooltip;
  const content = sourceView.querySelector(".cm-content");
  if (!state || !tooltip || !content) {
    return;
  }
  const contentRect = content.getBoundingClientRect();
  const tooltipRect = tooltip.getBoundingClientRect();
  let targetLeft = contentRect.left;
  if (state.alignment === "center") {
    targetLeft += (contentRect.width - tooltipRect.width) / 2;
  } else if (state.alignment === "right") {
    targetLeft = contentRect.right - tooltipRect.width;
  }
  const nativeLeft = tooltipRect.left - ((_a = state.translateX) != null ? _a : 0);
  state.translateX = targetLeft - nativeLeft;
  if (state.translateY === null) {
    state.translateY = state.targetTop - tooltipRect.top;
  }
  setTooltipTranslation(tooltip, state.translateX, state.translateY);
}
function clearNativeEditAlignment(sourceView) {
  disposeNativeEditAlignment(sourceView, true);
}
function disposeNativeEditAlignment(sourceView, shouldClearTooltips) {
  var _a;
  const state = nativeEditAlignmentStates.get(sourceView);
  if (!state) {
    return;
  }
  state.mutationObserver.disconnect();
  state.resizeObserver.disconnect();
  if (state.activationTimeoutId !== null) {
    ((_a = sourceView.ownerDocument.defaultView) != null ? _a : window).clearTimeout(
      state.activationTimeoutId
    );
  }
  if (shouldClearTooltips) {
    clearTooltipAlignment(state.previousTooltip);
    clearTooltipAlignment(state.tooltip);
  }
  nativeEditAlignmentStates.delete(sourceView);
}
function findNativeEditTooltips(sourceView) {
  return Array.from(
    sourceView.querySelectorAll(".cm-image-reveal-tooltip")
  ).filter((candidate) => candidate.querySelector(".image-embed"));
}
function clearTooltipAlignment(tooltip) {
  if (!tooltip) {
    return;
  }
  tooltip.removeAttribute(EDIT_TOOLTIP_ALIGNMENT_ATTRIBUTE);
  const originalTranslation = originalTooltipTranslations.get(tooltip);
  if (originalTranslation === void 0) {
    return;
  }
  if (originalTranslation) {
    tooltip.style.setProperty("translate", originalTranslation);
  } else {
    tooltip.style.removeProperty("translate");
  }
  originalTooltipTranslations.delete(tooltip);
}
function setTooltipTranslation(tooltip, translateX, translateY) {
  if (!originalTooltipTranslations.has(tooltip)) {
    originalTooltipTranslations.set(
      tooltip,
      tooltip.style.getPropertyValue("translate")
    );
  }
  tooltip.style.setProperty("translate", `${translateX}px ${translateY}px`);
}
function getImageAlignment(imageElement, defaultAlignment) {
  var _a;
  const alignment = ((_a = imageElement.getAttribute("alt")) != null ? _a : "").split("|").map((token) => token.trim().toLowerCase()).find(
    (token) => token === "left" || token === "center" || token === "right"
  );
  return alignment != null ? alignment : defaultAlignment;
}

// src/plugin-text.ts
var import_obsidian = require("obsidian");
var PLUGIN_TEXT = {
  en: {
    alignmentLabels: {
      center: "Center",
      left: "Left",
      right: "Right"
    },
    alignedNotice: (alignment) => `Image alignment set to ${PLUGIN_TEXT.en.alignmentLabels[alignment].toLowerCase()}.`,
    commandCenter: "Set current image centered",
    commandLeft: "Set current image left aligned",
    commandRight: "Set current image right aligned",
    calloutImageSizeSyncDesc: "When enabled, images inside callouts use their Obsidian width and height markers in Live Preview and Reading view.",
    calloutImageSizeSyncName: "Apply image size markers inside callouts",
    defaultAlignmentDesc: "Images without an explicit alignment marker use this default.",
    defaultAlignmentName: "Default image alignment",
    menuTitle: (alignment) => `Align image ${PLUGIN_TEXT.en.alignmentLabels[alignment].toLowerCase()}`,
    noImage: "No image found on the current selection or cursor line."
  },
  zh: {
    alignmentLabels: {
      center: "\u5C45\u4E2D",
      left: "\u5DE6\u5BF9\u9F50",
      right: "\u53F3\u5BF9\u9F50"
    },
    alignedNotice: (alignment) => `\u56FE\u7247\u5DF2\u8BBE\u7F6E\u4E3A${PLUGIN_TEXT.zh.alignmentLabels[alignment]}\u3002`,
    commandCenter: "\u5C06\u5F53\u524D\u56FE\u7247\u5C45\u4E2D",
    commandLeft: "\u5C06\u5F53\u524D\u56FE\u7247\u5DE6\u5BF9\u9F50",
    commandRight: "\u5C06\u5F53\u524D\u56FE\u7247\u53F3\u5BF9\u9F50",
    calloutImageSizeSyncDesc: "\u5F00\u542F\u540E\uFF0Ccallout \u5185\u56FE\u7247\u4F1A\u5728\u5B9E\u65F6\u9884\u89C8\u548C\u9605\u8BFB\u89C6\u56FE\u4E2D\u6309 Obsidian \u5BBD\u9AD8\u6807\u8BB0\u663E\u793A\u3002",
    calloutImageSizeSyncName: "\u8BA9 callout \u5185\u56FE\u7247\u5E94\u7528\u5C3A\u5BF8\u6807\u8BB0",
    defaultAlignmentDesc: "\u6CA1\u6709\u663E\u5F0F\u5BF9\u9F50\u6807\u8BB0\u7684\u56FE\u7247\u4F1A\u4F7F\u7528\u8FD9\u4E2A\u9ED8\u8BA4\u503C\u3002",
    defaultAlignmentName: "\u9ED8\u8BA4\u56FE\u7247\u5BF9\u9F50",
    menuTitle: (alignment) => `\u56FE\u7247${PLUGIN_TEXT.zh.alignmentLabels[alignment]}`,
    noImage: "\u5F53\u524D\u9009\u533A\u6216\u5149\u6807\u6240\u5728\u884C\u6CA1\u6709\u53EF\u8BBE\u7F6E\u5BF9\u9F50\u7684\u56FE\u7247\u3002"
  }
};
function getPluginText() {
  return PLUGIN_TEXT[getPluginLanguage()];
}
function getPluginLanguage() {
  return (0, import_obsidian.getLanguage)().toLowerCase().startsWith("zh") ? "zh" : "en";
}

// src/setting-tab.ts
var import_obsidian2 = require("obsidian");
var ImageAlignmentSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  getSettingDefinitions() {
    const text = this.plugin.getText();
    return [
      {
        name: text.defaultAlignmentName,
        desc: text.defaultAlignmentDesc,
        render: (setting) => {
          setting.addDropdown((dropdown) => {
            dropdown.addOption("center", text.alignmentLabels.center).addOption("left", text.alignmentLabels.left).addOption("right", text.alignmentLabels.right).setValue(this.plugin.settings.defaultAlignment).onChange(async (value) => {
              this.plugin.settings.defaultAlignment = value;
              await this.plugin.saveSettings();
            });
          });
        }
      },
      {
        name: text.calloutImageSizeSyncName,
        desc: text.calloutImageSizeSyncDesc,
        render: (setting) => {
          setting.addToggle((toggle) => {
            toggle.setValue(this.plugin.settings.syncCalloutImageSizes).onChange(async (value) => {
              this.plugin.settings.syncCalloutImageSizes = value;
              await this.plugin.saveSettings();
            });
          });
        }
      }
    ];
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  defaultAlignment: "center",
  syncCalloutImageSizes: true
};

// main.ts
var ImageAlignmentPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    __publicField(this, "settings", DEFAULT_SETTINGS);
    __publicField(this, "selectedImageElement", null);
    __publicField(this, "registeredDocuments", /* @__PURE__ */ new Set());
    __publicField(this, "calloutImageSizeObservers", /* @__PURE__ */ new Map());
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ImageAlignmentSettingTab(this.app, this));
    this.registerWorkspaceDocumentEvents();
    this.registerAlignmentCommands();
  }
  onunload() {
    for (const targetDocument of this.registeredDocuments) {
      clearImageAlignmentBodyClasses(targetDocument);
      clearCalloutImageSizeSync(targetDocument);
      clearLivePreviewImageEditPreviews(targetDocument);
    }
    this.disconnectCalloutImageSizeObservers();
  }
  getText() {
    return getPluginText();
  }
  registerAlignmentCommands() {
    this.addCommand({
      id: getAlignmentCommandId("left"),
      name: this.getText().commandLeft,
      editorCallback: (editor) => this.alignSelectedOrCurrentImage(editor, "left")
    });
    this.addCommand({
      id: getAlignmentCommandId("center"),
      name: this.getText().commandCenter,
      editorCallback: (editor) => this.alignSelectedOrCurrentImage(editor, "center")
    });
    this.addCommand({
      id: getAlignmentCommandId("right"),
      name: this.getText().commandRight,
      editorCallback: (editor) => this.alignSelectedOrCurrentImage(editor, "right")
    });
  }
  async loadSettings() {
    var _a, _b;
    const savedSettings = await this.loadData();
    this.settings = {
      defaultAlignment: (_a = savedSettings == null ? void 0 : savedSettings.defaultAlignment) != null ? _a : DEFAULT_SETTINGS.defaultAlignment,
      syncCalloutImageSizes: (_b = savedSettings == null ? void 0 : savedSettings.syncCalloutImageSizes) != null ? _b : DEFAULT_SETTINGS.syncCalloutImageSizes
    };
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.applyDefaultAlignmentClass();
    this.applyCalloutImageSizeSyncSetting();
  }
  applyDefaultAlignmentClass() {
    for (const targetDocument of this.registeredDocuments) {
      applyImageAlignmentBodyClasses(this.settings, targetDocument);
    }
  }
  registerWorkspaceDocumentEvents() {
    this.app.workspace.onLayoutReady(() => this.registerExistingWorkspaceDocuments());
    this.registerDocumentEvents(document);
    this.registerEvent(this.app.workspace.on("window-open", (_workspaceWindow, targetWindow) => {
      this.registerDocumentEvents(targetWindow.document);
    }));
    this.registerEvent(this.app.workspace.on("window-close", (_workspaceWindow, targetWindow) => {
      clearImageAlignmentBodyClasses(targetWindow.document);
      clearLivePreviewImageEditPreviews(targetWindow.document);
      this.disableCalloutImageSizeSync(targetWindow.document);
      this.registeredDocuments.delete(targetWindow.document);
    }));
  }
  registerExistingWorkspaceDocuments() {
    const documents = /* @__PURE__ */ new Set([document]);
    this.app.workspace.iterateAllLeaves((leaf) => {
      documents.add(leaf.getContainer().doc);
    });
    for (const targetDocument of documents) {
      this.registerDocumentEvents(targetDocument);
    }
  }
  registerDocumentEvents(targetDocument) {
    if (this.registeredDocuments.has(targetDocument)) {
      return;
    }
    this.registeredDocuments.add(targetDocument);
    applyImageAlignmentBodyClasses(this.settings, targetDocument);
    this.applyCalloutImageSizeSyncSetting(targetDocument);
    this.registerDomEvent(targetDocument, "contextmenu", (event) => this.captureImageContextMenu(event), true);
    this.registerDomEvent(targetDocument, "mousedown", (event) => this.captureSelectedImage(event), true);
    this.registerDomEvent(targetDocument, "pointerdown", (event) => {
      preserveLivePreviewImageDuringNativeEdit(event, this.settings.defaultAlignment);
    }, true);
    this.registerDomEvent(targetDocument, "click", (event) => {
      preserveLivePreviewImageDuringNativeEdit(event, this.settings.defaultAlignment);
    }, true);
  }
  applyCalloutImageSizeSyncSetting(targetDocument) {
    const documents = targetDocument ? [targetDocument] : Array.from(this.registeredDocuments);
    for (const documentToUpdate of documents) {
      if (this.settings.syncCalloutImageSizes) {
        this.enableCalloutImageSizeSync(documentToUpdate);
      } else {
        this.disableCalloutImageSizeSync(documentToUpdate);
      }
    }
  }
  enableCalloutImageSizeSync(targetDocument) {
    var _a;
    syncCalloutImageSizes(targetDocument);
    if (this.calloutImageSizeObservers.has(targetDocument)) {
      return;
    }
    const ownerWindow = (_a = targetDocument.defaultView) != null ? _a : window;
    const observer = new ownerWindow.MutationObserver(() => syncCalloutImageSizes(targetDocument));
    observer.observe(targetDocument.body, {
      attributeFilter: ["height", "src", "width"],
      attributes: true,
      childList: true,
      subtree: true
    });
    this.calloutImageSizeObservers.set(targetDocument, observer);
    this.register(() => observer.disconnect());
  }
  disableCalloutImageSizeSync(targetDocument) {
    var _a;
    (_a = this.calloutImageSizeObservers.get(targetDocument)) == null ? void 0 : _a.disconnect();
    this.calloutImageSizeObservers.delete(targetDocument);
    clearCalloutImageSizeSync(targetDocument);
  }
  disconnectCalloutImageSizeObservers() {
    for (const observer of this.calloutImageSizeObservers.values()) {
      observer.disconnect();
    }
    this.calloutImageSizeObservers.clear();
  }
  alignSelectedOrCurrentImage(editor, alignment) {
    var _a;
    const selectedTarget = (_a = this.findImageTargetFromSelectedElement()) != null ? _a : findImageInSelection(editor);
    if (selectedTarget) {
      this.alignImageTarget(selectedTarget, alignment);
      return;
    }
    const cursor = editor.getCursor();
    const line = editor.getLine(cursor.line);
    const match = findImageNearPosition(line, cursor.ch);
    if (!match) {
      new import_obsidian3.Notice(this.getText().noImage);
      return;
    }
    editor.replaceRange(
      setImageAlignment(match.value, alignment, this.settings.defaultAlignment),
      { line: cursor.line, ch: match.from },
      { line: cursor.line, ch: match.to }
    );
    this.showAlignedNotice(alignment);
  }
  captureImageContextMenu(event) {
    const target = event.target;
    if (!isHTMLElement(target)) {
      return;
    }
    const imageElement = target.closest(".image-embed, .internal-embed.image-embed, img");
    if (!imageElement || !isInMarkdownContent(imageElement)) {
      return;
    }
    const imageTarget = this.findImageTargetFromElement(imageElement);
    if (!imageTarget) {
      return;
    }
    const menu = import_obsidian3.Menu.forEvent(event);
    menu.addSeparator();
    for (const alignment of ["left", "center", "right"]) {
      menu.addItem((item) => {
        item.setTitle(this.getText().menuTitle(alignment)).onClick(() => this.alignImageTarget(imageTarget, alignment));
      });
    }
  }
  captureSelectedImage(event) {
    const target = event.target;
    if (!isHTMLElement(target)) {
      return;
    }
    const imageElement = target.closest(".image-embed, .internal-embed.image-embed, img");
    this.selectedImageElement = imageElement && isInMarkdownContent(imageElement) ? imageElement : null;
  }
  findImageTargetFromElement(element) {
    const imageSource = getImageSourceFromElement(element);
    if (!imageSource) {
      return null;
    }
    const owningView = this.getMarkdownViewContainingElement(element);
    if (owningView) {
      const occurrenceIndex = this.getImageSourceOccurrenceIndex(owningView, element, imageSource);
      if (occurrenceIndex !== null) {
        return this.findImageTargetBySource(owningView, imageSource, occurrenceIndex);
      }
      return this.findImageTargetBySource(owningView, imageSource, 0);
    }
    for (const view of this.getCandidateMarkdownViews()) {
      const imageTarget = this.findImageTargetBySource(view, imageSource, 0);
      if (imageTarget) {
        return imageTarget;
      }
    }
    return null;
  }
  getCandidateMarkdownViews() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    const views = activeView ? [activeView] : [];
    for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
      if (leaf.view instanceof import_obsidian3.MarkdownView && !views.includes(leaf.view)) {
        views.push(leaf.view);
      }
    }
    return views;
  }
  getMarkdownViewContainingElement(element) {
    var _a;
    return (_a = this.getCandidateMarkdownViews().find((view) => view.containerEl.contains(element))) != null ? _a : null;
  }
  getImageSourceOccurrenceIndex(view, element, imageSource) {
    var _a;
    const targetImageElement = (_a = element.closest(".image-embed")) != null ? _a : element;
    let occurrenceIndex = 0;
    for (const imageElement of view.containerEl.querySelectorAll(".image-embed")) {
      if (!isInMarkdownContent(imageElement) || getImageSourceFromElement(imageElement) !== imageSource) {
        continue;
      }
      if (imageElement === targetImageElement || imageElement.contains(targetImageElement)) {
        return occurrenceIndex;
      }
      occurrenceIndex += 1;
    }
    return null;
  }
  findImageTargetBySource(view, imageSource, occurrenceIndex) {
    let remainingMatches = occurrenceIndex;
    for (let lineNumber = 0; lineNumber < view.editor.lineCount(); lineNumber += 1) {
      const line = view.editor.getLine(lineNumber);
      for (const match of findImagesInLine(line)) {
        if (!imageMatchHasSource(match.value, imageSource)) {
          continue;
        }
        if (remainingMatches === 0) {
          return {
            editor: view.editor,
            line: lineNumber,
            match
          };
        }
        remainingMatches -= 1;
      }
    }
    return null;
  }
  findImageTargetFromSelectedElement() {
    if (!this.selectedImageElement || !this.selectedImageElement.isConnected) {
      return null;
    }
    return this.findImageTargetFromElement(this.selectedImageElement);
  }
  alignImageTarget(target, alignment) {
    target.editor.replaceRange(
      setImageAlignment(target.match.value, alignment, this.settings.defaultAlignment),
      { line: target.line, ch: target.match.from },
      { line: target.line, ch: target.match.to }
    );
    this.showAlignedNotice(alignment);
  }
  showAlignedNotice(alignment) {
    new import_obsidian3.Notice(this.getText().alignedNotice(alignment));
  }
};
function getAlignmentCommandId(alignment) {
  return `align-current-image-${alignment}`;
}


/* nosourcemap */